### ISSUE TITLE
Moving project to its own organization: a new name is needed

### ISSUE THREAD

**Issue by alkchr** [colegion/goal#30]
It is both possible to:
* Come up with the idea of an organization name but use the same toolkit name;
* Rename the toolkit, too.

My proposals are:
* `goaltools/goal` (`goaltools.com` domain is available)
* `goalproject/goal` (`.com`, `.org`, `.net` domains are taken)
* ~~`goaltech/goal` (both GH username `goaltech` and domains are taken)~~
* Rename back to `sunplate` (we have `sunplate.club` domain)

Other options are welcome.

**Comment by DavidHunter** [comment]
You don't want to use Colegion?

**Comment by alkchr** [comment]
@DavidHunter Apart from what we've discussed it is also possible to just move `colegion/contrib` to a separate `goalcontrib` organization. What do you think?

**Comment by DavidHunter** [comment]
Have 2 organization accounts for one project? Sounds confusing

**Comment by alkchr** [comment]
@DavidHunter This approach is quite popular. E.g. [go-martini/martini](https://github.com/go-martini/martini) (the framework itself) and [martini-contrib](https://github.com/martini-contrib) (the community contributed part).

**Comment by DavidHunter** [comment]
@alkchr I understand now. What do you think is the best approach right now?

**Comment by DavidHunter** [comment]
Are you moving colegion/goal to goaltools/goal?

**Comment by alkchr** [comment]
Yeah, but super slowly.

**Comment by alkchr** [comment]
I'm closing this as the issue is resolved. Stable packages will be extracted out into `goaltools` organisation. `colegion/goal` and `colegion/contrib` are a playground for experiments.
