### ISSUE TITLE
project is inactived?

### ISSUE THREAD

**Issue by runner-mei** [colegion/goal#43]

**Comment by alkchr** [comment]
Hello, @runner-mei. Thank you for the question.

I've invested about half a year of full time work into the project. So it was not easy, but eventually a decision to discontinue it and move on has been made. The project didn't satisfy my expectations regarding interest of community and my own priorities have changed over time.

Thanks everyone who participated and contributed to the discussions. @xpbliss, @DavidHunter

**Comment by runner-mei** [comment]
Thranks

**Comment by xpbliss** [comment]
Is it  actived or inactived?

**Comment by DavidHunter** [comment]
@alkchr I still have some interest in it.

**Comment by runner-mei** [comment]
@DavidHunter @xpbliss  can create revel2 base this

**Comment by runner-mei** [comment]
I like this project. I push two pull request #47 and #48

**Comment by alkchr** [comment]
@DavidHunter Related to what we've discussed in IRC. Apparently, there is no interest in cooperation on @revel's side. So, I'm going to continue working on Goal.

@runner-mei As for the PRs, I'll review #47 and #48 shortly. Thanks for contribution.
