### ISSUE TITLE
Document every tool

### ISSUE THREAD

**Issue by alkchr** [colegion/goal#6]
Manual lives [here](https://github.com/colegion/goal/tree/gh-pages/manual). The docs are for MVP but they are still valid. Every tool [here](https://github.com/colegion/goal/tree/master/tools) must have their own `README.md` as follows:
* tools/
  * run/
    * main.go
    * ...
    * README.md
  * new/
    * main.go
    * ...
    * README.md
  * ...

And we can have a list and short descriptions of all supported tools in the root README.md.

**Comment by DavidHunter** [comment]
Shouldn't this be at it's own repository?

**Comment by alkchr** [comment]
@DavidHunter Well' I don't know. Probably.

The idea was to simplify user's reading of code by providing a README for every subpackage in the repo. That would also help to keep the docs up-to-date: if you're contributing something, you're making changes not only to code, but also to the appropriate README.

But on the other hand, that would require maintaining two versions of docs: in this repo and web-site. And that looks like overkill.

What do you think? Separate repo?

**Comment by DavidHunter** [comment]
I looked at other open source projects and they have them in separate repo or its in the website repo. 

Mongodb has docs in a separate repo. You can git clone it and build a local html version. I think that is a nice feature.

**Comment by alkchr** [comment]
OK, let's use a separate repo then.

**Comment by DavidHunter** [comment]
It also depends on what you have planned for Colegion. Will you be building other products other then Goal toolkit?

**Comment by alkchr** [comment]
@DavidHunter Yes I will.

**Comment by DavidHunter** [comment]
We can have the docs in the projects repositories then just parse the docs in each project for the Colegion website.

**Comment by alkchr** [comment]
I will support any your decision regarding this issue.

**Comment by alkchr** [comment]
@DavidHunter, By the way we can rename the project and/or move it into a separate organization if that helps. E.g. how about goal+? `goalplus` is available GH username for a new organization.
And as for the domain, unfortunately `.toolkit` does not exist. But there is `.tk` (as in **t**ool**k**it). Though don't know whether we can trust it as it is 1) free, 2) the registrar doesn't have SSL certificate. On the other hand, they have a lot of good options such as `getgoal.tk`, `learngoal.tk`, `goalplus.tk`.
Or we can go with a more traditional but also longer `.com` domain. `goalplus.com`, `goalproject.com`, and `goaltoolkit.com` are taken, `goalplustoolkit.com` is free.

**Comment by alkchr** [comment]
@DavidHunter Are you still around and interested? If not I'm going to follow my initial plan.

**Comment by DavidHunter** [comment]
I am still around. Been busy with some stuff. I like the way you are doing things. I want to support your plans.

**Comment by alkchr** [comment]
@DavidHunter Great.

I'm closing this issue as we have already had some kind of documentation for every of the tools. Now we need to work on the quality of the documentation + probably redesign the web-site (orange color, icon with the Sun, etc. is all a legacy of the previous project name).
