### ISSUE TITLE
Define high level goals

### ISSUE THREAD

**Issue by alkchr** [colegion/goal#9]
Let's define the high level goals of the project. What are we trying to achieve? What are the priorities?

Can it be more than a traditional (by traditional I mean HTML template system as V) MVC framework? Probably, like [Meteor](https://www.meteor.com/), [Volt](http://voltframework.com/), [Webalchemy](https://github.com/skariel/webalchemy). Should it?
Or we can just make sure it works good with Angular, React, and whatever is fashionable now.

The code generation we are relying on is pretty powerful and we can do a lot of cool things. We just need to decide what cool things we want.

And to the question of positioning: is it a framework or toolkit? It is implemented in a form of separate tools. Every one is independent and can be used on its own. But on the other hand all of the tools play nicely with each other and form a single framework. So, how should we call it (need to know as it is used a lot in the comments and docs)? I have started with "toolkit" but recently switched to "framework".

**Comment by DavidHunter** [comment]
I like the idea of it being a toolkit. Originally I thought that is what you were building.

**Comment by alkchr** [comment]
I have decided to focus on things that work for me and my use cases instead of being "cool". As for the "framework" vs. "toolkit", there is a popular "golang is so special it doesn't need frameworks" mantra that we cannot help but take advantage of that. So, "toolkit".

**Comment by alkchr** [comment]
I have discovered [go-humble](https://github.com/go-humble/humble). Looks like they are doing the same thing we are but for front-end.
This is a note to myself to take a closer look to their project and find out whether it is possible to use go-humble and goal together. Or otherwise get inspiration to implement own alternatives to their tools.
